/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
    './packages/ui/src/**/*.{js,jsx}',
    './design-system/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        dark: {
          900: '#0a0e1a',
          800: '#0f1629',
          700: '#151d35',
          600: '#1a2540',
          500: '#243052',
        },
        accent: {
          blue: '#3b82f6',
          green: '#10b981',
          orange: '#f59e0b',
          purple: '#8b5cf6',
          red: '#ef4444',
          yellow: '#eab308',
        },
        ds: {
          primary: 'var(--ds-primary)',
          secondary: 'var(--ds-secondary)',
          bg: 'var(--ds-bg)',
          surface: 'var(--ds-surface)',
          border: 'var(--ds-border)',
          ink: 'var(--ds-ink)',
          muted: 'var(--ds-muted)',
          success: 'var(--ds-success)',
          warning: 'var(--ds-warning)',
          danger: 'var(--ds-danger)',
          info: 'var(--ds-info)',
          sky: 'var(--ds-sky)',
        },
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'ds-display-xl': ['var(--ds-font-display-xl)', { lineHeight: '1.15', fontWeight: '700' }],
        'ds-display': ['var(--ds-font-display)', { lineHeight: '1.15', fontWeight: '700' }],
        'ds-h1': ['var(--ds-font-h1)', { lineHeight: '1.2', fontWeight: '700' }],
        'ds-h2': ['var(--ds-font-h2)', { lineHeight: '1.2', fontWeight: '700' }],
        'ds-h3': ['var(--ds-font-h3)', { lineHeight: '1.25', fontWeight: '600' }],
        'ds-h4': ['var(--ds-font-h4)', { lineHeight: '1.25', fontWeight: '600' }],
        'ds-h5': ['var(--ds-font-h5)', { lineHeight: '1.3', fontWeight: '600' }],
        'ds-h6': ['var(--ds-font-h6)', { lineHeight: '1.35', fontWeight: '600' }],
        'ds-card-title': ['var(--ds-font-card-title)', { lineHeight: '1.35', fontWeight: '600' }],
        'ds-section': ['var(--ds-font-section-title)', { lineHeight: '1.4', fontWeight: '600' }],
        'ds-body-lg': ['var(--ds-font-body-lg)', { lineHeight: '1.5', fontWeight: '400' }],
        'ds-body': ['var(--ds-font-body)', { lineHeight: '1.5', fontWeight: '400' }],
        'ds-small': ['var(--ds-font-small)', { lineHeight: '1.4', fontWeight: '400' }],
        'ds-caption': ['var(--ds-font-caption)', { lineHeight: '1.4', fontWeight: '400' }],
        'ds-table': ['var(--ds-font-table-body)', { lineHeight: '1.4', fontWeight: '400' }],
        'ds-table-header': [
          'var(--ds-font-table-header)',
          { lineHeight: '1.4', fontWeight: '600' },
        ],
      },
      spacing: {
        'ds-1': 'var(--ds-space-1)',
        'ds-2': 'var(--ds-space-2)',
        'ds-3': 'var(--ds-space-3)',
        'ds-4': 'var(--ds-space-4)',
        'ds-5': 'var(--ds-space-5)',
        'ds-6': 'var(--ds-space-6)',
        'ds-8': 'var(--ds-space-8)',
        'ds-10': 'var(--ds-space-10)',
        'ds-12': 'var(--ds-space-12)',
        'ds-14': 'var(--ds-space-14)',
        'ds-16': 'var(--ds-space-16)',
        'ds-20': 'var(--ds-space-20)',
        'ds-24': 'var(--ds-space-24)',
        'ds-32': 'var(--ds-space-32)',
        'ds-sidebar': 'var(--ds-sidebar-expanded)',
        'ds-sidebar-mini': 'var(--ds-sidebar-collapsed)',
        'ds-header': 'var(--ds-header-h)',
      },
      borderRadius: {
        'ds-sm': 'var(--ds-radius-sm)',
        'ds-md': 'var(--ds-radius-md)',
        'ds-lg': 'var(--ds-radius-lg)',
        'ds-xl': 'var(--ds-radius-xl)',
        'ds-hero': 'var(--ds-radius-hero)',
        'ds-input': 'var(--ds-radius-input)',
        'ds-button': 'var(--ds-radius-button)',
        'ds-card': 'var(--ds-radius-card)',
        'ds-dialog': 'var(--ds-radius-dialog)',
        'ds-drawer': 'var(--ds-radius-drawer)',
        'ds-dropdown': 'var(--ds-radius-dropdown)',
      },
      boxShadow: {
        'ds-xs': 'var(--ds-shadow-xs)',
        'ds-sm': 'var(--ds-shadow-sm)',
        'ds-md': 'var(--ds-shadow-md)',
        'ds-lg': 'var(--ds-shadow-lg)',
        'ds-xl': 'var(--ds-shadow-xl)',
        'ds-layer-1': 'var(--ds-shadow-layer-1)',
        'ds-layer-2': 'var(--ds-shadow-layer-2)',
        'ds-layer-3': 'var(--ds-shadow-layer-3)',
      },
      minHeight: {
        control: 'var(--ds-control-h)',
      },
      height: {
        control: 'var(--ds-control-h)',
        header: 'var(--ds-header-h)',
      },
      width: {
        sidebar: 'var(--ds-sidebar-expanded)',
        'sidebar-mini': 'var(--ds-sidebar-collapsed)',
      },
      transitionDuration: {
        hover: '150ms',
        dropdown: '200ms',
        drawer: '300ms',
        page: '300ms',
      },
      zIndex: {
        dropdown: '1000',
        sticky: '1100',
        drawer: '1200',
        modal: '1300',
        toast: '1400',
        command: '1500',
      },
    },
  },
  plugins: [],
}
