export type AiosAgent = {
  id: string
  name: string
  role: string
  description: string
  modules: string[]
  defaultProvider: string
  defaultModel: string
  costLimitUsd: number
  permissions: string[]
  version: string
}

/** Standard agents — adding a new agent = append here (no core rewrite). */
export const AIOS_AGENTS: AiosAgent[] = [
  {
    id: 'ai.ceo',
    name: 'AI CEO',
    role: 'executive',
    description: 'Strateji, öncelikler ve çapraz modül özetleri.',
    modules: ['crm', 'sales', 'finance', 'ops', 'reporting'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 50,
    permissions: ['aios.chat', 'report.read'],
    version: '1.0.0',
  },
  {
    id: 'ai.ops_director',
    name: 'AI Operasyon Direktörü',
    role: 'operations',
    description: 'Üretim, depo, lojistik koordinasyonu.',
    modules: ['production', 'warehouse', 'logistics', 'quality'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 30,
    permissions: ['aios.chat', 'ops.read'],
    version: '1.0.0',
  },
  {
    id: 'ai.sales_manager',
    name: 'AI Satış Müdürü',
    role: 'sales',
    description: 'Teklif, pipeline ve kapanış önerileri.',
    modules: ['crm', 'quotes', 'orders'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 25,
    permissions: ['aios.chat', 'quote.draft', 'customer.search'],
    version: '1.0.0',
  },
  {
    id: 'ai.crm_specialist',
    name: 'AI CRM Uzmanı',
    role: 'crm',
    description: 'Müşteri 360, etiketleme, takip görevleri.',
    modules: ['crm'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'customer.search', 'task.update'],
    version: '1.0.0',
  },
  {
    id: 'ai.production_planner',
    name: 'AI Üretim Planlama Uzmanı',
    role: 'production',
    description: 'Kapasite ve iş emri planlama.',
    modules: ['production', 'orders'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'production.read'],
    version: '1.0.0',
  },
  {
    id: 'ai.quality',
    name: 'AI Kalite Uzmanı',
    role: 'quality',
    description: 'Kalite kontrol checklist ve sapma analizi.',
    modules: ['quality', 'production'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat', 'quality.read'],
    version: '1.0.0',
  },
  {
    id: 'ai.warehouse',
    name: 'AI Depo Uzmanı',
    role: 'warehouse',
    description: 'Stok, yerleştirme, sayım önerileri.',
    modules: ['warehouse', 'inventory'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat', 'inventory.search'],
    version: '1.0.0',
  },
  {
    id: 'ai.logistics',
    name: 'AI Lojistik Planlama Uzmanı',
    role: 'logistics',
    description: 'Rota, yük ve teslim planı.',
    modules: ['logistics'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'route.create', 'truck.load'],
    version: '1.0.0',
  },
  {
    id: 'ai.purchasing',
    name: 'AI Satın Alma Uzmanı',
    role: 'purchasing',
    description: 'Tedarik ve stok eşiği önerileri.',
    modules: ['purchasing', 'inventory'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat', 'inventory.search'],
    version: '1.0.0',
  },
  {
    id: 'ai.accounting',
    name: 'AI Muhasebe Uzmanı',
    role: 'accounting',
    description: 'Fatura taslağı ve mutabakat yardımcıları.',
    modules: ['accounting', 'finance'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'invoice.draft'],
    version: '1.0.0',
  },
  {
    id: 'ai.finance_analyst',
    name: 'AI Finans Analisti',
    role: 'finance',
    description: 'Nakit akışı ve risk özetleri.',
    modules: ['finance', 'reporting'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 25,
    permissions: ['aios.chat', 'report.read'],
    version: '1.0.0',
  },
  {
    id: 'ai.hr',
    name: 'AI İnsan Kaynakları Uzmanı',
    role: 'hr',
    description: 'PDKS, izin ve onboarding asistanı.',
    modules: ['hr'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 10,
    permissions: ['aios.chat'],
    version: '1.0.0',
  },
  {
    id: 'ai.marketing',
    name: 'AI Pazarlama Müdürü',
    role: 'marketing',
    description: 'Kampanya ve içerik planı.',
    modules: ['ai_growth', 'marketing'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 30,
    permissions: ['aios.chat'],
    version: '1.0.0',
  },
  {
    id: 'ai.seo',
    name: 'AI SEO Uzmanı',
    role: 'seo',
    description: 'SEO içerik ve anahtar kelime önerileri.',
    modules: ['ai_growth'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
  },
  {
    id: 'ai.social',
    name: 'AI Sosyal Medya Uzmanı',
    role: 'social',
    description: 'Sosyal içerik takvimi.',
    modules: ['ai_growth'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
  },
  {
    id: 'ai.ads',
    name: 'AI Reklam Uzmanı',
    role: 'ads',
    description: 'Reklam metni ve hedef kitle önerileri.',
    modules: ['ai_growth'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
  },
  {
    id: 'ai.design',
    name: 'AI Tasarım Asistanı',
    role: 'design',
    description: 'Görsel brief ve varyasyon önerileri.',
    modules: ['ai_growth', 'documents'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
  },
  {
    id: 'ai.document',
    name: 'AI Belge Asistanı',
    role: 'documents',
    description: 'Belge şablon ve özet.',
    modules: ['documents', 'print'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat', 'document.generate'],
    version: '1.0.0',
  },
  {
    id: 'ai.reporting',
    name: 'AI Raporlama Uzmanı',
    role: 'reporting',
    description: 'Yönetici raporları ve KPI özeti.',
    modules: ['reporting'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'report.read'],
    version: '1.0.0',
  },
  {
    id: 'ai.support',
    name: 'AI Destek Uzmanı',
    role: 'support',
    description: 'Ticket özeti ve yanıt taslağı.',
    modules: ['support'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
  },
  {
    id: 'ai.data_analyst',
    name: 'AI Veri Analisti',
    role: 'analytics',
    description: 'Veri keşfi ve anomaly açıklamaları.',
    modules: ['reporting', 'crm', 'finance'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 25,
    permissions: ['aios.chat', 'report.read'],
    version: '1.0.0',
  },
  {
    id: 'ai.translator',
    name: 'AI Çeviri Uzmanı',
    role: 'translation',
    description: 'Çok dilli belge ve iletişim çevirisi.',
    modules: ['crm', 'documents'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 10,
    permissions: ['aios.chat'],
    version: '1.0.0',
  },
  {
    id: 'ai.customer_comms',
    name: 'AI Müşteri İletişim Uzmanı',
    role: 'comms',
    description: 'Mail / WhatsApp taslakları (gönderim onayı ayrı).',
    modules: ['crm', 'omnichannel'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'email.draft', 'whatsapp.draft'],
    version: '1.0.0',
  },
]

export function getAgentById(id: string) {
  return AIOS_AGENTS.find((a) => a.id === id) || null
}
