export type OrgTier = 'ceo' | 'c_suite' | 'director' | 'specialist'

export type AiosAgent = {
  id: string
  name: string
  role: string
  description: string
  modules: string[]
  defaultProvider: string
  defaultModel: string
  costLimitUsd: number
  permissions: string[]
  version: string
  orgTier?: OrgTier
  /** Agent id this role reports to (org layer); communication still via Orchestrator only */
  reportsToAgentId?: string | null
}

/** Standard agents — adding a new agent = append here (no core rewrite). */
export const AIOS_AGENTS: AiosAgent[] = [
  {
    id: 'ai.ceo',
    name: 'AI CEO',
    role: 'executive',
    description:
      'Şirketin tamamını analiz eder; departman raporları, risk özeti, günlük yönetim brifingi.',
    modules: ['crm', 'sales', 'finance', 'ops', 'reporting', 'aios'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 50,
    permissions: ['aios.chat', 'report.read'],
    version: '1.1.0',
    orgTier: 'ceo',
    reportsToAgentId: null,
  },
  {
    id: 'ai.ops_director',
    name: 'AI COO',
    role: 'operations',
    description: 'Operasyonları yönetir; üretim, depo, lojistik, workflow optimizasyonu.',
    modules: ['production', 'warehouse', 'logistics', 'quality', 'workflow'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 35,
    permissions: ['aios.chat', 'ops.read'],
    version: '1.1.0',
    orgTier: 'c_suite',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.cfo',
    name: 'AI CFO',
    role: 'finance_executive',
    description: 'Finans, nakit, karlılık, kur riski, tahsilat ve maliyet analizi.',
    modules: ['finance', 'accounting', 'reporting'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 40,
    permissions: ['aios.chat', 'report.read', 'invoice.draft'],
    version: '1.0.0',
    orgTier: 'c_suite',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.cmo',
    name: 'AI CMO',
    role: 'marketing_executive',
    description: 'SEO, Ads, Instagram, YouTube, LinkedIn, TikTok içerik ve kampanya önerileri.',
    modules: ['ai_growth', 'marketing'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 35,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'c_suite',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.cto',
    name: 'AI CTO',
    role: 'technology_executive',
    description: 'Platform sağlığı, entegrasyonlar, AI Gateway ve güvenlik gözetimi.',
    modules: ['platform', 'aios', 'integrations'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 30,
    permissions: ['aios.chat', 'report.read'],
    version: '1.0.0',
    orgTier: 'c_suite',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.chro',
    name: 'AI CHRO',
    role: 'hr_executive',
    description: 'İK stratejisi, PDKS, kapasite ve vardiya riskleri.',
    modules: ['hr'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'c_suite',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.sales_manager',
    name: 'AI Sales Director',
    role: 'sales',
    description: 'Satış fırsatları, teklif, iskonto riski ve hedef takibi.',
    modules: ['crm', 'quotes', 'orders'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 25,
    permissions: ['aios.chat', 'quote.draft', 'customer.search'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.crm_specialist',
    name: 'AI CRM Director',
    role: 'crm',
    description: 'Müşteri ilişkileri, riskli müşteri ve sadakat önerileri.',
    modules: ['crm'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'customer.search', 'task.update'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.production_planner',
    name: 'AI Production Director',
    role: 'production',
    description: 'Üretim planı, darboğaz, fire, makine, operatör ve kapasite.',
    modules: ['production', 'orders'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'production.read'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ops_director',
  },
  {
    id: 'ai.quality',
    name: 'AI Quality Director',
    role: 'quality',
    description: 'Kalite kontrol, fire, fotoğraf analizi, iade ve AI Vision raporları.',
    modules: ['quality', 'production'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat', 'quality.read'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ops_director',
  },
  {
    id: 'ai.warehouse',
    name: 'AI Warehouse Director',
    role: 'warehouse',
    description: 'Stok, adresleme, sayım, FIFO, FEFO, ABC analizi.',
    modules: ['warehouse', 'inventory'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat', 'inventory.search'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ops_director',
  },
  {
    id: 'ai.logistics',
    name: 'AI Logistics Director',
    role: 'logistics',
    description: 'Tır doluluk, palet, koli, rota, yakıt, teslim süresi.',
    modules: ['logistics'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'route.create', 'truck.load'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ops_director',
  },
  {
    id: 'ai.purchasing',
    name: 'AI Purchasing Director',
    role: 'purchasing',
    description: 'Satın alma talepleri, tedarikçi performans, fiyat ve teslim analizi.',
    modules: ['purchasing', 'inventory'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat', 'inventory.search'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ops_director',
  },
  {
    id: 'ai.accounting',
    name: 'AI Muhasebe Uzmanı',
    role: 'accounting',
    description: 'Fatura taslağı ve mutabakat yardımcıları.',
    modules: ['accounting', 'finance'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'invoice.draft'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.cfo',
  },
  {
    id: 'ai.finance_analyst',
    name: 'AI Finans Analisti',
    role: 'finance',
    description: 'Nakit akışı ve risk özetleri.',
    modules: ['finance', 'reporting'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 25,
    permissions: ['aios.chat', 'report.read'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.cfo',
  },
  {
    id: 'ai.hr',
    name: 'AI İnsan Kaynakları Uzmanı',
    role: 'hr',
    description: 'PDKS, izin ve onboarding asistanı.',
    modules: ['hr'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 10,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.chro',
  },
  {
    id: 'ai.marketing',
    name: 'AI Pazarlama Müdürü',
    role: 'marketing',
    description: 'Kampanya ve içerik planı.',
    modules: ['ai_growth', 'marketing'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 30,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.cmo',
  },
  {
    id: 'ai.seo',
    name: 'AI SEO Uzmanı',
    role: 'seo',
    description: 'SEO içerik ve anahtar kelime önerileri.',
    modules: ['ai_growth'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.cmo',
  },
  {
    id: 'ai.social',
    name: 'AI Sosyal Medya Uzmanı',
    role: 'social',
    description: 'Sosyal içerik takvimi.',
    modules: ['ai_growth'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.cmo',
  },
  {
    id: 'ai.ads',
    name: 'AI Reklam Uzmanı',
    role: 'ads',
    description: 'Reklam metni ve hedef kitle önerileri.',
    modules: ['ai_growth'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.cmo',
  },
  {
    id: 'ai.design',
    name: 'AI Tasarım Asistanı',
    role: 'design',
    description: 'Görsel brief ve varyasyon önerileri.',
    modules: ['ai_growth', 'documents'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.cmo',
  },
  {
    id: 'ai.document',
    name: 'AI Belge Asistanı',
    role: 'documents',
    description: 'Belge şablon ve özet.',
    modules: ['documents', 'print'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat', 'document.generate'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.knowledge_director',
  },
  {
    id: 'ai.reporting',
    name: 'AI Raporlama Uzmanı',
    role: 'reporting',
    description: 'Yönetici raporları ve KPI özeti.',
    modules: ['reporting'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'report.read'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.data_analyst',
  },
  {
    id: 'ai.support',
    name: 'AI Support Director',
    role: 'support',
    description: 'Ticket analizi, SLA, memnuniyet ve yanıt kalitesi.',
    modules: ['support'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 15,
    permissions: ['aios.chat'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.data_analyst',
    name: 'AI Analytics Director',
    role: 'analytics',
    description: 'Dashboard yorumu, trend, tahmin ve KPI önerileri.',
    modules: ['reporting', 'crm', 'finance'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o',
    costLimitUsd: 25,
    permissions: ['aios.chat', 'report.read'],
    version: '1.1.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.knowledge_director',
    name: 'AI Knowledge Director',
    role: 'knowledge',
    description: 'Prosedür öğrenme, belge indeksleme, RAG bilgi tabanı güncelleme.',
    modules: ['knowledge', 'documents'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'knowledge.search'],
    version: '1.0.0',
    orgTier: 'director',
    reportsToAgentId: 'ai.cto',
  },
  {
    id: 'ai.translator',
    name: 'AI Çeviri Uzmanı',
    role: 'translation',
    description: 'Çok dilli belge ve iletişim çevirisi.',
    modules: ['crm', 'documents'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 10,
    permissions: ['aios.chat'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.ceo',
  },
  {
    id: 'ai.customer_comms',
    name: 'AI Müşteri İletişim Uzmanı',
    role: 'comms',
    description: 'Mail / WhatsApp taslakları (gönderim onayı ayrı).',
    modules: ['crm', 'omnichannel'],
    defaultProvider: 'openai',
    defaultModel: 'gpt-4o-mini',
    costLimitUsd: 20,
    permissions: ['aios.chat', 'email.draft', 'whatsapp.draft'],
    version: '1.0.0',
    orgTier: 'specialist',
    reportsToAgentId: 'ai.crm_specialist',
  },
]

export function getAgentById(id: string) {
  return AIOS_AGENTS.find((a) => a.id === id) || null
}
