import type { BlogTopicPlan } from './types'

/** Editorial backlog — 100+ GEO/SEO blog topic plans (not all published yet). */
export const BLOG_TOPIC_PLANS: BlogTopicPlan[] = [
  {
    title: 'CRM Nedir? 2026 Uygulamalı Rehber',
    slug: 'crm-nedir-rehberi',
    description: 'CRM kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'crm nedir',
    metaDescription: 'CRM kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'CRM',
    relatedModules: ['/crm'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'CRM Yönetiminde 7 Sık Hata',
    slug: 'crm-hatalar',
    description: 'İşletmelerin CRM süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'crm hataları',
    metaDescription:
      'İşletmelerin CRM süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'CRM',
    relatedModules: ['/crm'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'CRM için Takip Edilecek KPI’lar',
    slug: 'crm-kpi',
    description: 'CRM performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'crm kpi',
    metaDescription: 'CRM performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'CRM',
    relatedModules: ['/crm'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için CRM Kurulum Kontrol Listesi',
    slug: 'crm-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde CRM başlangıç adımları.',
    focusKeyword: 'kobi crm',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde CRM başlangıç adımları. BachMain Blog.',
    category: 'CRM',
    relatedModules: ['/crm'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut CRM Seçerken Nelere Bakmalı?',
    slug: 'crm-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut crm',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'CRM',
    relatedModules: ['/crm'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'CRM Entegrasyonu: API ve Webhook Temelleri',
    slug: 'crm-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'crm api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'CRM',
    relatedModules: ['/crm'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'CRM Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'crm-ai',
    description: 'AI’nın CRM işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'crm yapay zeka',
    metaDescription: 'AI’nın CRM işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'CRM',
    relatedModules: ['/crm'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'ERP Nedir? 2026 Uygulamalı Rehber',
    slug: 'erp-nedir-rehberi',
    description: 'ERP kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'erp nedir',
    metaDescription: 'ERP kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'ERP',
    relatedModules: ['/erp'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'ERP Yönetiminde 7 Sık Hata',
    slug: 'erp-hatalar',
    description: 'İşletmelerin ERP süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'erp hataları',
    metaDescription:
      'İşletmelerin ERP süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'ERP',
    relatedModules: ['/erp'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'ERP için Takip Edilecek KPI’lar',
    slug: 'erp-kpi',
    description: 'ERP performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'erp kpi',
    metaDescription: 'ERP performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'ERP',
    relatedModules: ['/erp'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için ERP Kurulum Kontrol Listesi',
    slug: 'erp-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde ERP başlangıç adımları.',
    focusKeyword: 'kobi erp',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde ERP başlangıç adımları. BachMain Blog.',
    category: 'ERP',
    relatedModules: ['/erp'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut ERP Seçerken Nelere Bakmalı?',
    slug: 'erp-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut erp',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'ERP',
    relatedModules: ['/erp'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'ERP Entegrasyonu: API ve Webhook Temelleri',
    slug: 'erp-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'erp api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'ERP',
    relatedModules: ['/erp'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'ERP Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'erp-ai',
    description: 'AI’nın ERP işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'erp yapay zeka',
    metaDescription: 'AI’nın ERP işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'ERP',
    relatedModules: ['/erp'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Stok Nedir? 2026 Uygulamalı Rehber',
    slug: 'stok-nedir-rehberi',
    description: 'Stok kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'stok nedir',
    metaDescription: 'Stok kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Stok',
    relatedModules: ['/stok'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Stok Yönetiminde 7 Sık Hata',
    slug: 'stok-hatalar',
    description: 'İşletmelerin Stok süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'stok hataları',
    metaDescription:
      'İşletmelerin Stok süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Stok',
    relatedModules: ['/stok'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Stok için Takip Edilecek KPI’lar',
    slug: 'stok-kpi',
    description: 'Stok performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'stok kpi',
    metaDescription: 'Stok performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Stok',
    relatedModules: ['/stok'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Stok Kurulum Kontrol Listesi',
    slug: 'stok-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Stok başlangıç adımları.',
    focusKeyword: 'kobi stok',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde Stok başlangıç adımları. BachMain Blog.',
    category: 'Stok',
    relatedModules: ['/stok'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Stok Seçerken Nelere Bakmalı?',
    slug: 'stok-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut stok',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Stok',
    relatedModules: ['/stok'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Stok Entegrasyonu: API ve Webhook Temelleri',
    slug: 'stok-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'stok api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Stok',
    relatedModules: ['/stok'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Stok Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'stok-ai',
    description: 'AI’nın Stok işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'stok yapay zeka',
    metaDescription: 'AI’nın Stok işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Stok',
    relatedModules: ['/stok'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Depo Nedir? 2026 Uygulamalı Rehber',
    slug: 'depo-nedir-rehberi',
    description: 'Depo kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'depo nedir',
    metaDescription: 'Depo kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Depo',
    relatedModules: ['/depo'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Depo Yönetiminde 7 Sık Hata',
    slug: 'depo-hatalar',
    description: 'İşletmelerin Depo süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'depo hataları',
    metaDescription:
      'İşletmelerin Depo süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Depo',
    relatedModules: ['/depo'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Depo için Takip Edilecek KPI’lar',
    slug: 'depo-kpi',
    description: 'Depo performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'depo kpi',
    metaDescription: 'Depo performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Depo',
    relatedModules: ['/depo'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Depo Kurulum Kontrol Listesi',
    slug: 'depo-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Depo başlangıç adımları.',
    focusKeyword: 'kobi depo',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde Depo başlangıç adımları. BachMain Blog.',
    category: 'Depo',
    relatedModules: ['/depo'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Depo Seçerken Nelere Bakmalı?',
    slug: 'depo-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut depo',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Depo',
    relatedModules: ['/depo'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Depo Entegrasyonu: API ve Webhook Temelleri',
    slug: 'depo-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'depo api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Depo',
    relatedModules: ['/depo'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Depo Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'depo-ai',
    description: 'AI’nın Depo işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'depo yapay zeka',
    metaDescription: 'AI’nın Depo işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Depo',
    relatedModules: ['/depo'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Üretim Nedir? 2026 Uygulamalı Rehber',
    slug: 'uretim-nedir-rehberi',
    description: 'Üretim kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'üretim nedir',
    metaDescription: 'Üretim kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Üretim',
    relatedModules: ['/uretim'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Üretim Yönetiminde 7 Sık Hata',
    slug: 'uretim-hatalar',
    description: 'İşletmelerin Üretim süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'üretim hataları',
    metaDescription:
      'İşletmelerin Üretim süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Üretim',
    relatedModules: ['/uretim'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Üretim için Takip Edilecek KPI’lar',
    slug: 'uretim-kpi',
    description: 'Üretim performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'üretim kpi',
    metaDescription: 'Üretim performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Üretim',
    relatedModules: ['/uretim'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Üretim Kurulum Kontrol Listesi',
    slug: 'uretim-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Üretim başlangıç adımları.',
    focusKeyword: 'kobi üretim',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde Üretim başlangıç adımları. BachMain Blog.',
    category: 'Üretim',
    relatedModules: ['/uretim'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Üretim Seçerken Nelere Bakmalı?',
    slug: 'uretim-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut üretim',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Üretim',
    relatedModules: ['/uretim'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Üretim Entegrasyonu: API ve Webhook Temelleri',
    slug: 'uretim-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'üretim api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Üretim',
    relatedModules: ['/uretim'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Üretim Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'uretim-ai',
    description: 'AI’nın Üretim işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'üretim yapay zeka',
    metaDescription: 'AI’nın Üretim işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Üretim',
    relatedModules: ['/uretim'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'E-Fatura Nedir? 2026 Uygulamalı Rehber',
    slug: 'e-fatura-nedir-rehberi',
    description: 'E-Fatura kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'e-fatura nedir',
    metaDescription: 'E-Fatura kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'E-Fatura',
    relatedModules: ['/e-fatura'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'E-Fatura Yönetiminde 7 Sık Hata',
    slug: 'e-fatura-hatalar',
    description: 'İşletmelerin E-Fatura süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'e-fatura hataları',
    metaDescription:
      'İşletmelerin E-Fatura süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'E-Fatura',
    relatedModules: ['/e-fatura'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'E-Fatura için Takip Edilecek KPI’lar',
    slug: 'e-fatura-kpi',
    description: 'E-Fatura performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'e-fatura kpi',
    metaDescription: 'E-Fatura performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'E-Fatura',
    relatedModules: ['/e-fatura'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için E-Fatura Kurulum Kontrol Listesi',
    slug: 'e-fatura-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde E-Fatura başlangıç adımları.',
    focusKeyword: 'kobi e-fatura',
    metaDescription:
      'Küçük ve orta ölçekli işletmelerde E-Fatura başlangıç adımları. BachMain Blog.',
    category: 'E-Fatura',
    relatedModules: ['/e-fatura'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut E-Fatura Seçerken Nelere Bakmalı?',
    slug: 'e-fatura-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut e-fatura',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'E-Fatura',
    relatedModules: ['/e-fatura'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'E-Fatura Entegrasyonu: API ve Webhook Temelleri',
    slug: 'e-fatura-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'e-fatura api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'E-Fatura',
    relatedModules: ['/e-fatura'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'E-Fatura Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'e-fatura-ai',
    description: 'AI’nın E-Fatura işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'e-fatura yapay zeka',
    metaDescription: 'AI’nın E-Fatura işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'E-Fatura',
    relatedModules: ['/e-fatura'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Muhasebe Nedir? 2026 Uygulamalı Rehber',
    slug: 'muhasebe-nedir-rehberi',
    description: 'Muhasebe kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'muhasebe nedir',
    metaDescription: 'Muhasebe kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Muhasebe',
    relatedModules: ['/muhasebe'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Muhasebe Yönetiminde 7 Sık Hata',
    slug: 'muhasebe-hatalar',
    description: 'İşletmelerin Muhasebe süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'muhasebe hataları',
    metaDescription:
      'İşletmelerin Muhasebe süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Muhasebe',
    relatedModules: ['/muhasebe'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Muhasebe için Takip Edilecek KPI’lar',
    slug: 'muhasebe-kpi',
    description: 'Muhasebe performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'muhasebe kpi',
    metaDescription: 'Muhasebe performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Muhasebe',
    relatedModules: ['/muhasebe'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Muhasebe Kurulum Kontrol Listesi',
    slug: 'muhasebe-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Muhasebe başlangıç adımları.',
    focusKeyword: 'kobi muhasebe',
    metaDescription:
      'Küçük ve orta ölçekli işletmelerde Muhasebe başlangıç adımları. BachMain Blog.',
    category: 'Muhasebe',
    relatedModules: ['/muhasebe'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Muhasebe Seçerken Nelere Bakmalı?',
    slug: 'muhasebe-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut muhasebe',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Muhasebe',
    relatedModules: ['/muhasebe'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Muhasebe Entegrasyonu: API ve Webhook Temelleri',
    slug: 'muhasebe-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'muhasebe api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Muhasebe',
    relatedModules: ['/muhasebe'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Muhasebe Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'muhasebe-ai',
    description: 'AI’nın Muhasebe işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'muhasebe yapay zeka',
    metaDescription: 'AI’nın Muhasebe işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Muhasebe',
    relatedModules: ['/muhasebe'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Cari Nedir? 2026 Uygulamalı Rehber',
    slug: 'cari-nedir-rehberi',
    description: 'Cari kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'cari nedir',
    metaDescription: 'Cari kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Cari',
    relatedModules: ['/cari'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Cari Yönetiminde 7 Sık Hata',
    slug: 'cari-hatalar',
    description: 'İşletmelerin Cari süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'cari hataları',
    metaDescription:
      'İşletmelerin Cari süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Cari',
    relatedModules: ['/cari'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Cari için Takip Edilecek KPI’lar',
    slug: 'cari-kpi',
    description: 'Cari performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'cari kpi',
    metaDescription: 'Cari performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Cari',
    relatedModules: ['/cari'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Cari Kurulum Kontrol Listesi',
    slug: 'cari-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Cari başlangıç adımları.',
    focusKeyword: 'kobi cari',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde Cari başlangıç adımları. BachMain Blog.',
    category: 'Cari',
    relatedModules: ['/cari'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Cari Seçerken Nelere Bakmalı?',
    slug: 'cari-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut cari',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Cari',
    relatedModules: ['/cari'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Cari Entegrasyonu: API ve Webhook Temelleri',
    slug: 'cari-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'cari api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Cari',
    relatedModules: ['/cari'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Cari Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'cari-ai',
    description: 'AI’nın Cari işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'cari yapay zeka',
    metaDescription: 'AI’nın Cari işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Cari',
    relatedModules: ['/cari'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Finans Nedir? 2026 Uygulamalı Rehber',
    slug: 'finans-nedir-rehberi',
    description: 'Finans kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'finans nedir',
    metaDescription: 'Finans kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Finans',
    relatedModules: ['/finans'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Finans Yönetiminde 7 Sık Hata',
    slug: 'finans-hatalar',
    description: 'İşletmelerin Finans süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'finans hataları',
    metaDescription:
      'İşletmelerin Finans süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Finans',
    relatedModules: ['/finans'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Finans için Takip Edilecek KPI’lar',
    slug: 'finans-kpi',
    description: 'Finans performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'finans kpi',
    metaDescription: 'Finans performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Finans',
    relatedModules: ['/finans'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Finans Kurulum Kontrol Listesi',
    slug: 'finans-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Finans başlangıç adımları.',
    focusKeyword: 'kobi finans',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde Finans başlangıç adımları. BachMain Blog.',
    category: 'Finans',
    relatedModules: ['/finans'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Finans Seçerken Nelere Bakmalı?',
    slug: 'finans-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut finans',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Finans',
    relatedModules: ['/finans'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Finans Entegrasyonu: API ve Webhook Temelleri',
    slug: 'finans-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'finans api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Finans',
    relatedModules: ['/finans'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Finans Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'finans-ai',
    description: 'AI’nın Finans işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'finans yapay zeka',
    metaDescription: 'AI’nın Finans işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Finans',
    relatedModules: ['/finans'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'WhatsApp Nedir? 2026 Uygulamalı Rehber',
    slug: 'whatsapp-nedir-rehberi',
    description: 'WhatsApp kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'whatsapp nedir',
    metaDescription: 'WhatsApp kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'WhatsApp',
    relatedModules: ['/whatsapp'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'WhatsApp Yönetiminde 7 Sık Hata',
    slug: 'whatsapp-hatalar',
    description: 'İşletmelerin WhatsApp süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'whatsapp hataları',
    metaDescription:
      'İşletmelerin WhatsApp süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'WhatsApp',
    relatedModules: ['/whatsapp'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'WhatsApp için Takip Edilecek KPI’lar',
    slug: 'whatsapp-kpi',
    description: 'WhatsApp performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'whatsapp kpi',
    metaDescription: 'WhatsApp performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'WhatsApp',
    relatedModules: ['/whatsapp'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için WhatsApp Kurulum Kontrol Listesi',
    slug: 'whatsapp-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde WhatsApp başlangıç adımları.',
    focusKeyword: 'kobi whatsapp',
    metaDescription:
      'Küçük ve orta ölçekli işletmelerde WhatsApp başlangıç adımları. BachMain Blog.',
    category: 'WhatsApp',
    relatedModules: ['/whatsapp'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut WhatsApp Seçerken Nelere Bakmalı?',
    slug: 'whatsapp-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut whatsapp',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'WhatsApp',
    relatedModules: ['/whatsapp'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'WhatsApp Entegrasyonu: API ve Webhook Temelleri',
    slug: 'whatsapp-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'whatsapp api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'WhatsApp',
    relatedModules: ['/whatsapp'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'WhatsApp Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'whatsapp-ai',
    description: 'AI’nın WhatsApp işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'whatsapp yapay zeka',
    metaDescription: 'AI’nın WhatsApp işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'WhatsApp',
    relatedModules: ['/whatsapp'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Lojistik Nedir? 2026 Uygulamalı Rehber',
    slug: 'lojistik-nedir-rehberi',
    description: 'Lojistik kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'lojistik nedir',
    metaDescription: 'Lojistik kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Lojistik',
    relatedModules: ['/lojistik'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Lojistik Yönetiminde 7 Sık Hata',
    slug: 'lojistik-hatalar',
    description: 'İşletmelerin Lojistik süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'lojistik hataları',
    metaDescription:
      'İşletmelerin Lojistik süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Lojistik',
    relatedModules: ['/lojistik'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Lojistik için Takip Edilecek KPI’lar',
    slug: 'lojistik-kpi',
    description: 'Lojistik performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'lojistik kpi',
    metaDescription: 'Lojistik performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Lojistik',
    relatedModules: ['/lojistik'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Lojistik Kurulum Kontrol Listesi',
    slug: 'lojistik-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Lojistik başlangıç adımları.',
    focusKeyword: 'kobi lojistik',
    metaDescription:
      'Küçük ve orta ölçekli işletmelerde Lojistik başlangıç adımları. BachMain Blog.',
    category: 'Lojistik',
    relatedModules: ['/lojistik'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Lojistik Seçerken Nelere Bakmalı?',
    slug: 'lojistik-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut lojistik',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Lojistik',
    relatedModules: ['/lojistik'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Lojistik Entegrasyonu: API ve Webhook Temelleri',
    slug: 'lojistik-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'lojistik api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Lojistik',
    relatedModules: ['/lojistik'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Lojistik Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'lojistik-ai',
    description: 'AI’nın Lojistik işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'lojistik yapay zeka',
    metaDescription: 'AI’nın Lojistik işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Lojistik',
    relatedModules: ['/lojistik'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Saha Satış Nedir? 2026 Uygulamalı Rehber',
    slug: 'saha-satis-nedir-rehberi',
    description: 'Saha Satış kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'saha satış nedir',
    metaDescription: 'Saha Satış kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Saha Satış',
    relatedModules: ['/saha-satis'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Saha Satış Yönetiminde 7 Sık Hata',
    slug: 'saha-satis-hatalar',
    description: 'İşletmelerin Saha Satış süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'saha satış hataları',
    metaDescription:
      'İşletmelerin Saha Satış süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Saha Satış',
    relatedModules: ['/saha-satis'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Saha Satış için Takip Edilecek KPI’lar',
    slug: 'saha-satis-kpi',
    description: 'Saha Satış performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'saha satış kpi',
    metaDescription: 'Saha Satış performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Saha Satış',
    relatedModules: ['/saha-satis'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Saha Satış Kurulum Kontrol Listesi',
    slug: 'saha-satis-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Saha Satış başlangıç adımları.',
    focusKeyword: 'kobi saha satış',
    metaDescription:
      'Küçük ve orta ölçekli işletmelerde Saha Satış başlangıç adımları. BachMain Blog.',
    category: 'Saha Satış',
    relatedModules: ['/saha-satis'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Saha Satış Seçerken Nelere Bakmalı?',
    slug: 'saha-satis-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut saha satış',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Saha Satış',
    relatedModules: ['/saha-satis'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Saha Satış Entegrasyonu: API ve Webhook Temelleri',
    slug: 'saha-satis-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'saha satış api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Saha Satış',
    relatedModules: ['/saha-satis'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Saha Satış Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'saha-satis-ai',
    description: 'AI’nın Saha Satış işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'saha satış yapay zeka',
    metaDescription: 'AI’nın Saha Satış işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Saha Satış',
    relatedModules: ['/saha-satis'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Yapay Zeka Nedir? 2026 Uygulamalı Rehber',
    slug: 'openai-nedir-rehberi',
    description: 'Yapay Zeka kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'yapay zeka nedir',
    metaDescription: 'Yapay Zeka kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Yapay Zeka',
    relatedModules: ['/openai'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Yapay Zeka Yönetiminde 7 Sık Hata',
    slug: 'openai-hatalar',
    description: 'İşletmelerin Yapay Zeka süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'yapay zeka hataları',
    metaDescription:
      'İşletmelerin Yapay Zeka süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Yapay Zeka',
    relatedModules: ['/openai'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Yapay Zeka için Takip Edilecek KPI’lar',
    slug: 'openai-kpi',
    description: 'Yapay Zeka performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'yapay zeka kpi',
    metaDescription: 'Yapay Zeka performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Yapay Zeka',
    relatedModules: ['/openai'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Yapay Zeka Kurulum Kontrol Listesi',
    slug: 'openai-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Yapay Zeka başlangıç adımları.',
    focusKeyword: 'kobi yapay zeka',
    metaDescription:
      'Küçük ve orta ölçekli işletmelerde Yapay Zeka başlangıç adımları. BachMain Blog.',
    category: 'Yapay Zeka',
    relatedModules: ['/openai'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Yapay Zeka Seçerken Nelere Bakmalı?',
    slug: 'openai-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut yapay zeka',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Yapay Zeka',
    relatedModules: ['/openai'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Yapay Zeka Entegrasyonu: API ve Webhook Temelleri',
    slug: 'openai-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'yapay zeka api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Yapay Zeka',
    relatedModules: ['/openai'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Yapay Zeka Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'openai-ai',
    description: 'AI’nın Yapay Zeka işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'yapay zeka yapay zeka',
    metaDescription: 'AI’nın Yapay Zeka işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Yapay Zeka',
    relatedModules: ['/openai'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Dashboard Nedir? 2026 Uygulamalı Rehber',
    slug: 'dashboard-nedir-rehberi',
    description: 'Dashboard kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'dashboard nedir',
    metaDescription: 'Dashboard kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Dashboard',
    relatedModules: ['/dashboard'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Dashboard Yönetiminde 7 Sık Hata',
    slug: 'dashboard-hatalar',
    description: 'İşletmelerin Dashboard süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'dashboard hataları',
    metaDescription:
      'İşletmelerin Dashboard süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Dashboard',
    relatedModules: ['/dashboard'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Dashboard için Takip Edilecek KPI’lar',
    slug: 'dashboard-kpi',
    description: 'Dashboard performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'dashboard kpi',
    metaDescription: 'Dashboard performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Dashboard',
    relatedModules: ['/dashboard'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Dashboard Kurulum Kontrol Listesi',
    slug: 'dashboard-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Dashboard başlangıç adımları.',
    focusKeyword: 'kobi dashboard',
    metaDescription:
      'Küçük ve orta ölçekli işletmelerde Dashboard başlangıç adımları. BachMain Blog.',
    category: 'Dashboard',
    relatedModules: ['/dashboard'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Dashboard Seçerken Nelere Bakmalı?',
    slug: 'dashboard-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut dashboard',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Dashboard',
    relatedModules: ['/dashboard'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Dashboard Entegrasyonu: API ve Webhook Temelleri',
    slug: 'dashboard-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'dashboard api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Dashboard',
    relatedModules: ['/dashboard'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Dashboard Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'dashboard-ai',
    description: 'AI’nın Dashboard işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'dashboard yapay zeka',
    metaDescription: 'AI’nın Dashboard işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Dashboard',
    relatedModules: ['/dashboard'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'B2B Nedir? 2026 Uygulamalı Rehber',
    slug: 'bayi-nedir-rehberi',
    description: 'B2B kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'b2b nedir',
    metaDescription: 'B2B kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'B2B',
    relatedModules: ['/bayi'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'B2B Yönetiminde 7 Sık Hata',
    slug: 'bayi-hatalar',
    description: 'İşletmelerin B2B süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'b2b hataları',
    metaDescription:
      'İşletmelerin B2B süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'B2B',
    relatedModules: ['/bayi'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'B2B için Takip Edilecek KPI’lar',
    slug: 'bayi-kpi',
    description: 'B2B performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'b2b kpi',
    metaDescription: 'B2B performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'B2B',
    relatedModules: ['/bayi'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için B2B Kurulum Kontrol Listesi',
    slug: 'bayi-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde B2B başlangıç adımları.',
    focusKeyword: 'kobi b2b',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde B2B başlangıç adımları. BachMain Blog.',
    category: 'B2B',
    relatedModules: ['/bayi'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut B2B Seçerken Nelere Bakmalı?',
    slug: 'bayi-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut b2b',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'B2B',
    relatedModules: ['/bayi'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'B2B Entegrasyonu: API ve Webhook Temelleri',
    slug: 'bayi-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'b2b api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'B2B',
    relatedModules: ['/bayi'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'B2B Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'bayi-ai',
    description: 'AI’nın B2B işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'b2b yapay zeka',
    metaDescription: 'AI’nın B2B işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'B2B',
    relatedModules: ['/bayi'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'Teklif Nedir? 2026 Uygulamalı Rehber',
    slug: 'teklif-nedir-rehberi',
    description: 'Teklif kavramını sade dille anlatan öğretici rehber.',
    focusKeyword: 'teklif nedir',
    metaDescription: 'Teklif kavramını sade dille anlatan öğretici rehber. BachMain Blog.',
    category: 'Teklif',
    relatedModules: ['/teklif'],
    outline: ['Nedir', 'Ne işe yarar', 'Kimler kullanır', 'Örnek senaryo', 'BachMain bağlantısı'],
  },
  {
    title: 'Teklif Yönetiminde 7 Sık Hata',
    slug: 'teklif-hatalar',
    description: 'İşletmelerin Teklif süreçlerinde yaptığı yaygın hatalar ve düzeltmeler.',
    focusKeyword: 'teklif hataları',
    metaDescription:
      'İşletmelerin Teklif süreçlerinde yaptığı yaygın hatalar ve düzeltmeler. BachMain Blog.',
    category: 'Teklif',
    relatedModules: ['/teklif'],
    outline: ['Hata listesi', 'Neden olur', 'Nasıl düzeltilir', 'Kontrol listesi'],
  },
  {
    title: 'Teklif için Takip Edilecek KPI’lar',
    slug: 'teklif-kpi',
    description: 'Teklif performansını ölçmek için pratik gösterge seti.',
    focusKeyword: 'teklif kpi',
    metaDescription: 'Teklif performansını ölçmek için pratik gösterge seti. BachMain Blog.',
    category: 'Teklif',
    relatedModules: ['/teklif'],
    outline: ['KPI seçimi', 'Hesaplama', 'Dashboard', 'Haftalık ritüel'],
  },
  {
    title: 'KOBİ’ler için Teklif Kurulum Kontrol Listesi',
    slug: 'teklif-kobi',
    description: 'Küçük ve orta ölçekli işletmelerde Teklif başlangıç adımları.',
    focusKeyword: 'kobi teklif',
    metaDescription: 'Küçük ve orta ölçekli işletmelerde Teklif başlangıç adımları. BachMain Blog.',
    category: 'Teklif',
    relatedModules: ['/teklif'],
    outline: ['Hazırlık', 'Master data', 'Pilot', 'Yaygınlaştırma'],
  },
  {
    title: 'Bulut Teklif Seçerken Nelere Bakmalı?',
    slug: 'teklif-bulut',
    description: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları.',
    focusKeyword: 'bulut teklif',
    metaDescription: 'Bulut yazılım seçim kriterleri ve değerlendirme soruları. BachMain Blog.',
    category: 'Teklif',
    relatedModules: ['/teklif'],
    outline: ['Güvenlik', 'Entegrasyon', 'Fiyat', 'Destek'],
  },
  {
    title: 'Teklif Entegrasyonu: API ve Webhook Temelleri',
    slug: 'teklif-entegrasyon',
    description: 'Sistemler arası veri akışının temelleri.',
    focusKeyword: 'teklif api',
    metaDescription: 'Sistemler arası veri akışının temelleri. BachMain Blog.',
    category: 'Teklif',
    relatedModules: ['/teklif'],
    outline: ['API', 'Webhook', 'Hata yönetimi', 'Örnek akış'],
  },
  {
    title: 'Teklif Süreçlerinde Yapay Zekâ Kullanımı',
    slug: 'teklif-ai',
    description: 'AI’nın Teklif işlerinde güvenli ve faydalı kullanımı.',
    focusKeyword: 'teklif yapay zeka',
    metaDescription: 'AI’nın Teklif işlerinde güvenli ve faydalı kullanımı. BachMain Blog.',
    category: 'Teklif',
    relatedModules: ['/teklif'],
    outline: ['Kullanım alanları', 'Riskler', 'İnsan onayı', 'Örnekler'],
  },
  {
    title: 'CRM ile ERP Arasındaki Fark Nedir?',
    slug: 'crm-erp-farki',
    description: 'İki kavramın sınırları, kesişim noktaları ve ne zaman birlikte kullanılacağı.',
    focusKeyword: 'crm erp farkı',
    metaDescription:
      'İki kavramın sınırları, kesişim noktaları ve ne zaman birlikte kullanılacağı. BachMain.',
    category: 'Genel',
    relatedModules: ['/crm', '/erp'],
    outline: ['Tanımlar', 'Fark tablosu', 'Ortak veri', 'BachMain yaklaşımı'],
  },
  {
    title: 'KOBİ’lerde Dijital Dönüşüm: Gerçekçi Yol Haritası',
    slug: 'dijital-donusum-kobi',
    description: 'Abartısız, adım adım dijitalleşme planı.',
    focusKeyword: 'kobi dijital dönüşüm',
    metaDescription: 'Abartısız, adım adım dijitalleşme planı. BachMain.',
    category: 'Genel',
    relatedModules: ['/demo', '/fiyatlar'],
    outline: ['Hedef', 'Pilot', 'Pilot', 'Ölçüm'],
  },
  {
    title: 'Yazılım Seçerken Helpful Content Mantığıyla Değerlendirme',
    slug: 'helpful-content-is-yazilimi',
    description: 'Pazarlama iddiası yerine kanıt ve kullanım senaryosuyla seçim.',
    focusKeyword: 'yazılım seçimi',
    metaDescription: 'Pazarlama iddiası yerine kanıt ve kullanım senaryosuyla seçim. BachMain.',
    category: 'Genel',
    relatedModules: ['/knowledge', '/blog'],
    outline: ['Kanıt', 'Demo', 'Referans', 'Toplam sahip olma maliyeti'],
  },
]

export function listBlogTopicPlans(): BlogTopicPlan[] {
  return BLOG_TOPIC_PLANS
}
