/** SaaS Integration Center — platform catalog (no customer-facing API keys). */

export const INTEGRATION_CATEGORIES = [
  { id: 'messaging', label: 'Mesajlaşma' },
  { id: 'social', label: 'Sosyal Medya' },
  { id: 'email', label: 'E-posta' },
  { id: 'ecommerce', label: 'E-Ticaret' },
  { id: 'erp', label: 'ERP / Muhasebe' },
  { id: 'payment', label: 'Ödeme' },
  { id: 'cargo', label: 'Kargo' },
  { id: 'einvoice', label: 'E-Fatura' },
  { id: 'banking', label: 'Banka' },
  { id: 'ai', label: 'Yapay Zeka' },
]

export const OAUTH_PROVIDERS = {
  meta: { label: 'Meta', durationSec: 30 },
  google: { label: 'Google', durationSec: 25 },
  microsoft: { label: 'Microsoft', durationSec: 25 },
  telegram: { label: 'Telegram', durationSec: 40 },
  tiktok: { label: 'TikTok', durationSec: 35 },
  linkedin: { label: 'LinkedIn', durationSec: 30 },
  x: { label: 'X', durationSec: 30 },
  shopify: { label: 'Shopify', durationSec: 35 },
  custom: { label: 'BachMain', durationSec: 20 },
}

/**
 * @typedef {object} IntegrationPlatform
 * @property {string} id
 * @property {string} title
 * @property {string} category
 * @property {string} brandKey
 * @property {string} brandColor
 * @property {string} summary
 * @property {string[]} permissions
 * @property {keyof typeof OAUTH_PROVIDERS} oauthProvider
 * @property {'available'|'beta'|'coming'} status
 * @property {boolean} [socialMessage]
 * @property {{ id: string, label: string, meta?: string }[]} [demoAccounts]
 */

/** @type {IntegrationPlatform[]} */
export const INTEGRATION_PLATFORMS = [
  {
    id: 'whatsapp',
    title: 'WhatsApp Business',
    category: 'messaging',
    brandKey: 'whatsapp',
    brandColor: '#25D366',
    summary: 'Müşterilerinizle WhatsApp üzerinden konuşmaya başlayın.',
    permissions: ['Mesaj gönderme/alma', 'Şablon mesajları', 'Webhook'],
    oauthProvider: 'meta',
    status: 'available',
    socialMessage: true,
    demoAccounts: [
      { id: 'wa-1', label: '+90 530 128 56 10', meta: 'BachMain Demo' },
      { id: 'wa-2', label: '+90 555 000 11 22', meta: 'Satış Hattı' },
    ],
  },
  {
    id: 'instagram',
    title: 'Instagram',
    category: 'social',
    brandKey: 'instagram',
    brandColor: '#E1306C',
    summary: 'DM, yorum ve içerik yayınını tek yerden yönetin.',
    permissions: ['Mesajlar', 'Yorumlar', 'Medya yayınlama', 'İçgörüler'],
    oauthProvider: 'meta',
    status: 'available',
    socialMessage: true,
    demoAccounts: [
      { id: 'ig-1', label: '@abcmobilya', meta: '12.4K takipçi' },
      { id: 'ig-2', label: '@abcmobilya.tr', meta: '3.1K takipçi' },
    ],
  },
  {
    id: 'facebook',
    title: 'Facebook',
    category: 'social',
    brandKey: 'facebook',
    brandColor: '#1877F2',
    summary: 'Sayfa gönderileri, yorumlar ve reklam hesaplarını bağlayın.',
    permissions: ['Sayfa yönetimi', 'Yorumlar', 'İçgörüler'],
    oauthProvider: 'meta',
    status: 'available',
    socialMessage: true,
    demoAccounts: [
      { id: 'fb-1', label: 'ABC Mobilya', meta: 'Sayfa' },
      { id: 'fb-2', label: 'ABC Showroom', meta: 'Sayfa' },
    ],
  },
  {
    id: 'messenger',
    title: 'Messenger',
    category: 'messaging',
    brandKey: 'facebook',
    brandColor: '#0084FF',
    summary: 'Facebook Messenger gelen kutusu BachMain Mesaj Merkezi’nde.',
    permissions: ['Mesaj gönderme/alma', 'Webhook'],
    oauthProvider: 'meta',
    status: 'available',
    socialMessage: true,
    demoAccounts: [{ id: 'msg-1', label: 'ABC Mobilya Messenger', meta: 'Sayfa bağlı' }],
  },
  {
    id: 'telegram',
    title: 'Telegram',
    category: 'messaging',
    brandKey: 'telegram',
    brandColor: '#26A5E4',
    summary: 'Bot veya iş hesabınızı OAuth benzeri akışla bağlayın.',
    permissions: ['Mesajlar', 'Bot komutları'],
    oauthProvider: 'telegram',
    status: 'beta',
    socialMessage: true,
    demoAccounts: [{ id: 'tg-1', label: '@abcmobilya_bot', meta: 'Bot' }],
  },
  {
    id: 'x',
    title: 'X (Twitter)',
    category: 'social',
    brandKey: 'x',
    brandColor: '#000000',
    summary: 'DM ve mention yanıtlarını tek gelen kutuda toplayın.',
    permissions: ['DM', 'Tweet okuma', 'Yanıt'],
    oauthProvider: 'x',
    status: 'beta',
    socialMessage: true,
    demoAccounts: [{ id: 'x-1', label: '@abcmobilya', meta: 'Hesap' }],
  },
  {
    id: 'linkedin',
    title: 'LinkedIn',
    category: 'social',
    brandKey: 'linkedin',
    brandColor: '#0A66C2',
    summary: 'Şirket sayfası mesajları ve yayınları.',
    permissions: ['Sayfa mesajları', 'Paylaşım'],
    oauthProvider: 'linkedin',
    status: 'beta',
    socialMessage: true,
    demoAccounts: [{ id: 'li-1', label: 'ABC Mobilya', meta: 'Company Page' }],
  },
  {
    id: 'tiktok',
    title: 'TikTok',
    category: 'social',
    brandKey: 'tiktok',
    brandColor: '#010101',
    summary: 'İşletme hesabı ve içerik senkronizasyonu.',
    permissions: ['İçerik', 'Yorumlar', 'İstatistik'],
    oauthProvider: 'tiktok',
    status: 'beta',
    socialMessage: true,
    demoAccounts: [{ id: 'tt-1', label: '@abcmobilya', meta: 'Business' }],
  },
  {
    id: 'gmail',
    title: 'Gmail',
    category: 'email',
    brandKey: 'gmail',
    brandColor: '#EA4335',
    summary: 'Google hesabınızla tek tıkla bağlanın — API anahtarı yok.',
    permissions: ['E-posta okuma/gönderme', 'Etiketler'],
    oauthProvider: 'google',
    status: 'available',
    socialMessage: true,
    demoAccounts: [
      { id: 'gm-1', label: 'info@abcmobilya.com', meta: 'Google Workspace' },
      { id: 'gm-2', label: 'satis@abcmobilya.com', meta: 'Gmail' },
    ],
  },
  {
    id: 'outlook',
    title: 'Outlook',
    category: 'email',
    brandKey: 'outlook',
    brandColor: '#0078D4',
    summary: 'Microsoft 365 / Outlook ile güvenli OAuth bağlantısı.',
    permissions: ['Mail okuma/gönderme', 'Takvim'],
    oauthProvider: 'microsoft',
    status: 'available',
    socialMessage: true,
    demoAccounts: [{ id: 'out-1', label: 'destek@abcmobilya.com', meta: 'Microsoft 365' }],
  },
  {
    id: 'webchat',
    title: 'Web Chat',
    category: 'messaging',
    brandKey: 'webchat',
    brandColor: '#0ea5e9',
    summary: 'Sitenize gömülü canlı sohbet widget’ı.',
    permissions: ['Widget', 'Ziyaretçi sohbeti'],
    oauthProvider: 'custom',
    status: 'available',
    socialMessage: true,
    demoAccounts: [{ id: 'wc-1', label: 'Varsayılan Widget', meta: 'bachmain.com' }],
  },
  {
    id: 'live-support',
    title: 'Canlı Destek',
    category: 'messaging',
    brandKey: 'live',
    brandColor: '#10b981',
    summary: 'BachMain canlı destek kanalını aktifleştirin.',
    permissions: ['Canlı oturum', 'Transfer'],
    oauthProvider: 'custom',
    status: 'available',
    socialMessage: true,
    demoAccounts: [{ id: 'ls-1', label: 'Ana Destek Kuyruğu', meta: '7/24' }],
  },
  {
    id: 'parasut',
    title: 'Paraşüt',
    category: 'erp',
    brandKey: 'parasut',
    brandColor: '#5B2C6F',
    summary: 'Fatura ve cari senkronizasyonu.',
    permissions: ['Faturalar', 'Cari'],
    oauthProvider: 'custom',
    status: 'beta',
    demoAccounts: [{ id: 'pr-1', label: 'ABC Mobilya Ltd.', meta: 'Şirket' }],
  },
  {
    id: 'logo',
    title: 'Logo',
    category: 'erp',
    brandKey: 'logo',
    brandColor: '#E30613',
    summary: 'Logo ERP stok ve sipariş entegrasyonu.',
    permissions: ['Stok', 'Sipariş', 'Cari'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'mikro',
    title: 'Mikro',
    category: 'erp',
    brandKey: 'mikro',
    brandColor: '#003366',
    summary: 'Mikro muhasebe / ERP bağlantısı.',
    permissions: ['Muhasebe', 'Stok'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'nebim',
    title: 'Nebim',
    category: 'erp',
    brandKey: 'nebim',
    brandColor: '#1B4F72',
    summary: 'Nebim V3 / Winner entegrasyonu.',
    permissions: ['Satış', 'Stok'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'eta',
    title: 'ETA',
    category: 'erp',
    brandKey: 'eta',
    brandColor: '#117A65',
    summary: 'ETA e-fatura ve muhasebe.',
    permissions: ['E-fatura', 'Muhasebe'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'sap',
    title: 'SAP',
    category: 'erp',
    brandKey: 'sap',
    brandColor: '#0FAAFF',
    summary: 'SAP B1 / S4 bağlantısı.',
    permissions: ['Master data', 'Sipariş'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'trendyol',
    title: 'Trendyol',
    category: 'ecommerce',
    brandKey: 'trendyol',
    brandColor: '#F27A1A',
    summary: 'Sipariş ve stok pazaryeri senkronu.',
    permissions: ['Sipariş', 'Stok', 'İade'],
    oauthProvider: 'custom',
    status: 'beta',
    demoAccounts: [{ id: 'ty-1', label: 'ABC Mobilya Magaza', meta: 'Satıcı' }],
  },
  {
    id: 'hepsiburada',
    title: 'Hepsiburada',
    category: 'ecommerce',
    brandKey: 'hepsiburada',
    brandColor: '#FF6000',
    summary: 'Hepsiburada satıcı API’si.',
    permissions: ['Sipariş', 'Stok'],
    oauthProvider: 'custom',
    status: 'beta',
  },
  {
    id: 'amazon',
    title: 'Amazon',
    category: 'ecommerce',
    brandKey: 'amazon',
    brandColor: '#FF9900',
    summary: 'Amazon Seller Central.',
    permissions: ['Sipariş', 'Envanter'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'n11',
    title: 'N11',
    category: 'ecommerce',
    brandKey: 'n11',
    brandColor: '#7B1FA2',
    summary: 'N11 mağaza bağlantısı.',
    permissions: ['Sipariş', 'Stok'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'woocommerce',
    title: 'WooCommerce',
    category: 'ecommerce',
    brandKey: 'woocommerce',
    brandColor: '#96588A',
    summary: 'WordPress mağazanızı bağlayın.',
    permissions: ['Ürün', 'Sipariş'],
    oauthProvider: 'custom',
    status: 'beta',
  },
  {
    id: 'shopify',
    title: 'Shopify',
    category: 'ecommerce',
    brandKey: 'shopify',
    brandColor: '#96BF48',
    summary: 'Shopify mağaza OAuth.',
    permissions: ['Ürün', 'Sipariş', 'Müşteri'],
    oauthProvider: 'shopify',
    status: 'beta',
    demoAccounts: [{ id: 'sh-1', label: 'abcmobilya.myshopify.com', meta: 'Store' }],
  },
  {
    id: 'iyzico',
    title: 'İyzico',
    category: 'payment',
    brandKey: 'iyzico',
    brandColor: '#1E88E5',
    summary: 'Ödeme ve iade webhook’ları.',
    permissions: ['Ödeme', 'İade'],
    oauthProvider: 'custom',
    status: 'beta',
  },
  {
    id: 'paytr',
    title: 'PayTR',
    category: 'payment',
    brandKey: 'paytr',
    brandColor: '#E53935',
    summary: 'PayTR sanal POS.',
    permissions: ['Ödeme', 'Bildirim'],
    oauthProvider: 'custom',
    status: 'beta',
  },
  {
    id: 'stripe',
    title: 'Stripe',
    category: 'payment',
    brandKey: 'stripe',
    brandColor: '#635BFF',
    summary: 'Stripe Connect OAuth.',
    permissions: ['Ödeme', 'Müşteri', 'Webhook'],
    oauthProvider: 'custom',
    status: 'available',
    demoAccounts: [{ id: 'st-1', label: 'acct_demo_abc', meta: 'Connect' }],
  },
  {
    id: 'mng',
    title: 'MNG Kargo',
    category: 'cargo',
    brandKey: 'mng',
    brandColor: '#C62828',
    summary: 'Kargo oluşturma ve takip.',
    permissions: ['Gönderi', 'Takip'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'yurtici',
    title: 'Yurtiçi Kargo',
    category: 'cargo',
    brandKey: 'yurtici',
    brandColor: '#F9A825',
    summary: 'Yurtiçi gönderi API.',
    permissions: ['Gönderi', 'Takip'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'aras',
    title: 'Aras Kargo',
    category: 'cargo',
    brandKey: 'aras',
    brandColor: '#E65100',
    summary: 'Aras kargo entegrasyonu.',
    permissions: ['Gönderi', 'Takip'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'ups',
    title: 'UPS',
    category: 'cargo',
    brandKey: 'ups',
    brandColor: '#351C15',
    summary: 'UPS uluslararası gönderi.',
    permissions: ['Gönderi', 'Takip'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'dhl',
    title: 'DHL',
    category: 'cargo',
    brandKey: 'dhl',
    brandColor: '#FFCC00',
    summary: 'DHL Express.',
    permissions: ['Gönderi', 'Takip'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'hepsijet',
    title: 'HepsiJet',
    category: 'cargo',
    brandKey: 'hepsijet',
    brandColor: '#FF6000',
    summary: 'HepsiJet teslimat.',
    permissions: ['Gönderi', 'Takip'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'surat',
    title: 'Sürat Kargo',
    category: 'cargo',
    brandKey: 'surat',
    brandColor: '#1565C0',
    summary: 'Sürat kargo API.',
    permissions: ['Gönderi', 'Takip'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'kolaysoft',
    title: 'Kolaysoft',
    category: 'einvoice',
    brandKey: 'kolaysoft',
    brandColor: '#00897B',
    summary: 'E-fatura / e-arşiv.',
    permissions: ['E-fatura', 'E-arşiv'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'edm',
    title: 'EDM',
    category: 'einvoice',
    brandKey: 'edm',
    brandColor: '#3949AB',
    summary: 'EDM e-belge.',
    permissions: ['E-fatura'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'foriba',
    title: 'Foriba',
    category: 'einvoice',
    brandKey: 'foriba',
    brandColor: '#6A1B9A',
    summary: 'Foriba e-dönüşüm.',
    permissions: ['E-fatura'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'qnb',
    title: 'QNB',
    category: 'banking',
    brandKey: 'qnb',
    brandColor: '#7B1FA2',
    summary: 'Banka hesap hareketleri.',
    permissions: ['Hesap hareketi'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'isbank',
    title: 'İş Bankası',
    category: 'banking',
    brandKey: 'isbank',
    brandColor: '#0033A0',
    summary: 'İş Bankası API.',
    permissions: ['Hesap hareketi'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'garanti',
    title: 'Garanti',
    category: 'banking',
    brandKey: 'garanti',
    brandColor: '#00A651',
    summary: 'Garanti BBVA Open Banking.',
    permissions: ['Hesap hareketi'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'akbank',
    title: 'Akbank',
    category: 'banking',
    brandKey: 'akbank',
    brandColor: '#E30613',
    summary: 'Akbank API.',
    permissions: ['Hesap hareketi'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'enpara',
    title: 'Enpara',
    category: 'banking',
    brandKey: 'enpara',
    brandColor: '#FF6F00',
    summary: 'Enpara hesap bağlantısı.',
    permissions: ['Hesap hareketi'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'papara',
    title: 'Papara',
    category: 'banking',
    brandKey: 'papara',
    brandColor: '#7C4DFF',
    summary: 'Papara ödeme / cüzdan.',
    permissions: ['Ödeme', 'Bakiye'],
    oauthProvider: 'custom',
    status: 'coming',
  },
  {
    id: 'openai',
    title: 'OpenAI',
    category: 'ai',
    brandKey: 'openai',
    brandColor: '#10A37F',
    summary: 'BachMain AI Gateway üzerinden OpenAI.',
    permissions: ['Chat', 'Embedding'],
    oauthProvider: 'custom',
    status: 'available',
    demoAccounts: [{ id: 'ai-1', label: 'BachMain AI Gateway', meta: 'Tenant key' }],
  },
  {
    id: 'claude',
    title: 'Claude',
    category: 'ai',
    brandKey: 'claude',
    brandColor: '#D97757',
    summary: 'Anthropic Claude.',
    permissions: ['Chat'],
    oauthProvider: 'custom',
    status: 'available',
  },
  {
    id: 'gemini',
    title: 'Gemini',
    category: 'ai',
    brandKey: 'gemini',
    brandColor: '#4285F4',
    summary: 'Google Gemini.',
    permissions: ['Chat'],
    oauthProvider: 'google',
    status: 'available',
  },
  {
    id: 'deepseek',
    title: 'DeepSeek',
    category: 'ai',
    brandKey: 'deepseek',
    brandColor: '#4D6BFE',
    summary: 'DeepSeek modelleri.',
    permissions: ['Chat'],
    oauthProvider: 'custom',
    status: 'beta',
  },
  {
    id: 'mistral',
    title: 'Mistral',
    category: 'ai',
    brandKey: 'mistral',
    brandColor: '#FF7000',
    summary: 'Mistral AI.',
    permissions: ['Chat'],
    oauthProvider: 'custom',
    status: 'beta',
  },
  {
    id: 'cursor-ai',
    title: 'Cursor AI',
    category: 'ai',
    brandKey: 'cursor',
    brandColor: '#000000',
    summary: 'Cursor ajan / SDK bağlantısı.',
    permissions: ['Agent'],
    oauthProvider: 'custom',
    status: 'coming',
  },
]

export function getPlatformById(id) {
  return INTEGRATION_PLATFORMS.find((p) => p.id === id) || null
}

export function listSocialMessagePlatforms() {
  return INTEGRATION_PLATFORMS.filter((p) => p.socialMessage)
}

export function listPlatformsByCategory(categoryId) {
  if (!categoryId || categoryId === 'all') return INTEGRATION_PLATFORMS
  return INTEGRATION_PLATFORMS.filter((p) => p.category === categoryId)
}
