/**
 * Module codes used for plan entitlements and CRM sidebar gating.
 * Prices/assignments are dynamic; codes are stable identifiers.
 */

export const MODULE_CATALOG = [
  { code: 'crm', label: 'CRM / Müşteri Yönetimi', group: 'core' },
  { code: 'quotes', label: 'Teklif', group: 'core' },
  { code: 'orders', label: 'Sipariş', group: 'core' },
  { code: 'accounts', label: 'Cari Hesap', group: 'core' },
  { code: 'tasks', label: 'Görev', group: 'core' },
  { code: 'calendar', label: 'Takvim', group: 'core' },
  { code: 'notes', label: 'Not Defteri', group: 'core' },
  { code: 'appointments', label: 'Randevu', group: 'core' },
  { code: 'dashboard_basic', label: 'Temel Dashboard', group: 'core' },
  { code: 'reports_basic', label: 'Temel Raporlar', group: 'core' },
  { code: 'production', label: 'Üretim', group: 'ops' },
  { code: 'warehouse', label: 'Depo', group: 'ops' },
  { code: 'barcode', label: 'Barkod', group: 'ops' },
  { code: 'stock', label: 'Stok', group: 'ops' },
  { code: 'purchasing', label: 'Satın Alma', group: 'ops' },
  { code: 'sales', label: 'Satış', group: 'ops' },
  { code: 'pos', label: 'POS', group: 'ops' },
  { code: 'finance', label: 'Finans', group: 'ops' },
  { code: 'einvoice', label: 'e-Fatura', group: 'ops' },
  { code: 'earchive', label: 'e-Arşiv', group: 'ops' },
  { code: 'ewaybill', label: 'e-İrsaliye', group: 'ops' },
  { code: 'esign', label: 'E-İmza', group: 'ops' },
  { code: 'field_sales', label: 'Saha Satış', group: 'ops' },
  { code: 'dealer', label: 'Bayi Yönetimi', group: 'ops' },
  { code: 'b2b', label: 'B2B Portal', group: 'ops' },
  { code: 'whatsapp', label: 'WhatsApp', group: 'comms' },
  { code: 'sms', label: 'SMS', group: 'comms' },
  { code: 'courier', label: 'Kurye', group: 'ops' },
  { code: 'api', label: 'API', group: 'platform' },
  { code: 'api_advanced', label: 'Gelişmiş API', group: 'platform' },
  { code: 'webhook', label: 'Webhook', group: 'platform' },
  { code: 'dashboard_advanced', label: 'Gelişmiş Dashboard', group: 'platform' },
  { code: 'bi', label: 'BI Dashboard', group: 'platform' },
  { code: 'ai', label: 'Yapay Zeka / AI Asistan', group: 'platform' },
  { code: 'hr', label: 'İnsan Kaynakları', group: 'enterprise' },
  { code: 'mrp', label: 'MRP', group: 'enterprise' },
  { code: 'quality', label: 'Kalite Yönetimi', group: 'enterprise' },
  { code: 'approvals', label: 'Onay Süreçleri', group: 'enterprise' },
  { code: 'workflows', label: 'İş Akışları', group: 'enterprise' },
  { code: 'multi_company', label: 'Çoklu Şirket', group: 'enterprise' },
  { code: 'multi_branch', label: 'Çoklu Şube', group: 'enterprise' },
  { code: 'multi_warehouse', label: 'Çoklu Depo', group: 'enterprise' },
  { code: 'multi_currency', label: 'Çoklu Para Birimi', group: 'enterprise' },
  { code: 'truck', label: 'Tır Yönetimi', group: 'enterprise' },
  { code: 'pallet', label: 'Palet Yönetimi', group: 'enterprise' },
  { code: 'parcel', label: 'Koli Yönetimi', group: 'enterprise' },
  { code: 'packaging', label: 'Paket Yönetimi', group: 'enterprise' },
  { code: 'container', label: 'Konteyner', group: 'enterprise' },
  { code: 'reporting', label: 'Raporlama', group: 'platform' },
  { code: 'priority_support', label: 'Öncelikli Destek', group: 'support' },
  { code: 'sla', label: 'SLA Desteği', group: 'support' },
  { code: 'dedicated_am', label: 'Özel Müşteri Temsilcisi', group: 'support' },
  { code: 'website_os', label: 'Website OS / Site Builder', group: 'website' },
]

export const STARTER_MODULES = [
  'crm',
  'quotes',
  'orders',
  'accounts',
  'tasks',
  'calendar',
  'notes',
  'appointments',
  'dashboard_basic',
  'reports_basic',
]

export const PROFESSIONAL_EXTRA = [
  'production',
  'warehouse',
  'barcode',
  'stock',
  'purchasing',
  'sales',
  'pos',
  'finance',
  'einvoice',
  'earchive',
  'field_sales',
  'dealer',
  'b2b',
  'whatsapp',
  'sms',
  'api',
  'dashboard_advanced',
  'reporting',
  'priority_support',
  'courier',
  'ewaybill',
  'esign',
]

export const ENTERPRISE_EXTRA = [
  'hr',
  'mrp',
  'quality',
  'approvals',
  'workflows',
  'multi_company',
  'multi_branch',
  'multi_warehouse',
  'multi_currency',
  'truck',
  'pallet',
  'parcel',
  'packaging',
  'container',
  'api_advanced',
  'webhook',
  'bi',
  'ai',
  'sla',
  'dedicated_am',
  'website_os',
]

export function modulesForPlan(code) {
  const c = String(code || '').toLowerCase()
  if (c === 'enterprise' || c === 'kurumsal') {
    return [...new Set([...STARTER_MODULES, ...PROFESSIONAL_EXTRA, ...ENTERPRISE_EXTRA])]
  }
  if (c === 'professional' || c === 'pro' || c === 'profesyonel') {
    return [...new Set([...STARTER_MODULES, ...PROFESSIONAL_EXTRA])]
  }
  return [...STARTER_MODULES]
}

/**
 * Modül Mağazası (bachmain.com/paketler/moduller) — satılabilir SaaS modülleri.
 * E-Fatura / AI kontör bu listede satılmaz; ayrı sayfalardadır.
 */
export const STORE_CATEGORIES = [
  { id: 'all', label: 'Tümü' },
  { id: 'crm_sales', label: 'CRM & Satış' },
  { id: 'finance', label: 'Finans' },
  { id: 'erp', label: 'ERP' },
  { id: 'production', label: 'Üretim' },
  { id: 'warehouse', label: 'Depo' },
  { id: 'logistics', label: 'Lojistik' },
  { id: 'b2b', label: 'B2B' },
  { id: 'hr', label: 'İnsan Kaynakları' },
  { id: 'comms', label: 'İletişim' },
  { id: 'management', label: 'Yönetim' },
  { id: 'integration', label: 'Entegrasyon' },
]

/** @type {Array<Record<string, unknown>>} */
export const STORE_MODULES = [
  {
    code: 'crm',
    slug: 'crm',
    label: 'CRM',
    category: 'crm_sales',
    icon: 'Users',
    iconColor: '#2563EB',
    description: 'Müşteri kartları, fırsatlar ve temel satış süreçlerini tek merkezden yönetin.',
    longDescription:
      'CRM modülü ile müşteri ilişkilerinizi, görüşme geçmişinizi ve satış fırsatlarınızı tek panelde takip edin. Temel pipeline ve görevlerle satış ekibinizi hızlandırın.',
    audience: 'Satış ekipleri, KOBİ’ler, müşteri ilişkisi odaklı firmalar',
    features: ['Müşteri kartları', 'Temel pipeline', 'Görüşme geçmişi', 'Görevler'],
    monthlyPrice: 199,
    yearlyPrice: 1990,
    trialDays: 14,
    sortOrder: 10,
    storeVisible: true,
  },
  {
    code: 'crm_pro',
    slug: 'crm-pro',
    label: 'CRM Pro',
    category: 'crm_sales',
    icon: 'Briefcase',
    iconColor: '#059669',
    description: 'Gelişmiş müşteri yönetimi, satış fırsatları ve pipeline’ı tek merkezden yönetin.',
    longDescription:
      'CRM Pro; gelişmiş fırsat yönetimi, çok aşamalı satış pipeline’ı, görev takibi ve satış raporlarıyla satış organizasyonunuzu güçlendirir.',
    audience: 'Büyüyen satış ekipleri ve profesyonel CRM ihtiyacı olan firmalar',
    features: ['Müşteri yönetimi', 'Satış pipeline', 'Görev takibi', 'Raporlama'],
    monthlyPrice: 249,
    yearlyPrice: 2490,
    trialDays: 14,
    sortOrder: 20,
    storeVisible: true,
  },
  {
    code: 'field_sales',
    slug: 'saha-satis',
    label: 'Saha Satış',
    category: 'crm_sales',
    icon: 'MapPin',
    iconColor: '#0284C7',
    description: 'Saha temsilcilerinizin ziyaret, sipariş ve tahsilatlarını mobil takip edin.',
    longDescription:
      'Saha Satış modülü ile temsilci rotaları, müşteri ziyaretleri, yerinde sipariş ve tahsilat süreçlerini canlı izleyin.',
    audience: 'Saha satış ekipleri, dağıtım ve toptan satış firmaları',
    features: ['Temsilci takibi', 'Ziyaret kayıtları', 'Mobil sipariş', 'Tahsilat'],
    monthlyPrice: 299,
    yearlyPrice: 2990,
    trialDays: 7,
    sortOrder: 30,
    storeVisible: true,
  },
  {
    code: 'quotes',
    slug: 'teklif-yonetimi',
    label: 'Teklif Yönetimi',
    category: 'crm_sales',
    icon: 'FileText',
    iconColor: '#7C3AED',
    description: 'Revizyonlu teklifler hazırlayın, onaylayın ve siparişe dönüştürün.',
    longDescription:
      'Teklif şablonları, versiyonlama, iskonto kuralları ve müşteri önizleme ile satış tekliflerinizi profesyonelleştirin.',
    audience: 'Satış ve teklif ekipleri',
    features: ['Şablon teklifler', 'Revizyon', 'İskonto kuralları', 'Siparişe dönüşüm'],
    monthlyPrice: 179,
    yearlyPrice: 1790,
    trialDays: 14,
    sortOrder: 40,
    storeVisible: true,
  },
  {
    code: 'orders',
    slug: 'siparis-yonetimi',
    label: 'Sipariş Yönetimi',
    category: 'crm_sales',
    icon: 'ShoppingCart',
    iconColor: '#EA580C',
    description: 'Siparişleri oluşturun, durumlarını izleyin ve operasyona aktarın.',
    longDescription:
      'Sipariş Yönetimi ile tekliften sevkiyata kadar sipariş yaşam döngüsünü tek akışta yönetin.',
    audience: 'Satış, müşteri hizmetleri ve operasyon ekipleri',
    features: ['Sipariş oluşturma', 'Durum takibi', 'Kalem yönetimi', 'Operasyon aktarımı'],
    monthlyPrice: 219,
    yearlyPrice: 2190,
    trialDays: 14,
    sortOrder: 50,
    storeVisible: true,
  },
  {
    code: 'production',
    slug: 'uretim',
    label: 'Üretim',
    category: 'production',
    icon: 'Factory',
    iconColor: '#B45309',
    description: 'İş emirleri, üretim aşamaları ve kapasiteyi tek panelden takip edin.',
    longDescription:
      'Üretim modülü ile iş emri, aşama takibi, fotoğraflı ilerleme ve maliyet görünürlüğü sağlayın.',
    audience: 'Üretim ve imalat firmaları',
    features: ['İş emirleri', 'Aşama takibi', 'Kapasite', 'Maliyet'],
    monthlyPrice: 349,
    yearlyPrice: 3490,
    trialDays: 7,
    sortOrder: 60,
    storeVisible: true,
  },
  {
    code: 'warehouse',
    slug: 'depo',
    label: 'Depo',
    category: 'warehouse',
    icon: 'Warehouse',
    iconColor: '#0D9488',
    description: 'Stok, depo hareketleri ve transferleri kolayca yönetin.',
    longDescription:
      'Temel depo yönetimi: stok kartları, giriş-çıkış, transfer ve kritik stok uyarıları.',
    audience: 'Depo ve stok operasyonları',
    features: ['Stok kartları', 'Depo hareketleri', 'Transfer', 'Kritik stok'],
    monthlyPrice: 229,
    yearlyPrice: 2290,
    trialDays: 14,
    sortOrder: 70,
    storeVisible: true,
  },
  {
    code: 'warehouse_pro',
    slug: 'gelismis-depo',
    label: 'Gelişmiş Depo',
    category: 'warehouse',
    icon: 'Boxes',
    iconColor: '#0891B2',
    description: 'Çoklu depo, barkod ve gelişmiş stok operasyonlarıyla deponuzu ölçekleyin.',
    longDescription:
      'Gelişmiş Depo; çoklu depo, barkod, lot/seri ve gelişmiş sayım süreçlerini içerir.',
    audience: 'Çok depolu ve yoğun lojistik operasyonlar',
    features: ['Çoklu depo', 'Barkod', 'Sayım', 'Lot / seri'],
    monthlyPrice: 329,
    yearlyPrice: 3290,
    trialDays: 7,
    sortOrder: 80,
    storeVisible: true,
  },
  {
    code: 'logistics',
    slug: 'lojistik',
    label: 'Lojistik',
    category: 'logistics',
    icon: 'Truck',
    iconColor: '#DC2626',
    description: 'Sevkiyat planlama, araç ve rota süreçlerini yönetin.',
    longDescription:
      'Lojistik modülü ile sevkiyat planları, araç atamaları ve teslimat durumlarını izleyin.',
    audience: 'Lojistik ve dağıtım ekipleri',
    features: ['Sevkiyat planı', 'Araç yönetimi', 'Rota', 'Teslimat durumu'],
    monthlyPrice: 279,
    yearlyPrice: 2790,
    trialDays: 7,
    sortOrder: 90,
    storeVisible: true,
  },
  {
    code: 'shipping',
    slug: 'sevkiyat',
    label: 'Sevkiyat',
    category: 'logistics',
    icon: 'Package',
    iconColor: '#E11D48',
    description: 'İrsaliye ve sevkiyat belgelerini hızlıca oluşturup takip edin.',
    longDescription:
      'Sevkiyat belgesi, irsaliye ve teslim onaylarını satış/depo ile entegre yönetin.',
    audience: 'Sevkiyat ve depo ekipleri',
    features: ['İrsaliye', 'Sevkiyat belgesi', 'Teslim onayı', 'Durum takibi'],
    monthlyPrice: 199,
    yearlyPrice: 1990,
    trialDays: 14,
    sortOrder: 100,
    storeVisible: true,
  },
  {
    code: 'b2b',
    slug: 'b2b-portal',
    label: 'B2B Portal',
    category: 'b2b',
    icon: 'Store',
    iconColor: '#4F46E5',
    description: 'Bayi ve müşterilerinizin online sipariş portalını açın.',
    longDescription:
      'B2B Portal ile bayileriniz fiyat listesine göre sipariş verebilir; stok ve cari bakiyeyi görür.',
    audience: 'Toptan satış, bayi ağı olan firmalar',
    features: ['Bayi portalı', 'Online sipariş', 'Fiyat listesi', 'Cari görünüm'],
    monthlyPrice: 299,
    yearlyPrice: 2990,
    trialDays: 7,
    sortOrder: 110,
    storeVisible: true,
  },
  {
    code: 'pos',
    slug: 'pos',
    label: 'POS',
    category: 'crm_sales',
    icon: 'MonitorSmartphone',
    iconColor: '#DB2777',
    description: 'Mağaza satış noktası ile hızlı tahsilat ve fiş süreçleri.',
    longDescription: 'POS ile perakende satış, hızlı ürün seçimi ve tahsilat işlemlerini yönetin.',
    audience: 'Perakende ve mağaza satışları',
    features: ['Hızlı satış', 'Tahsilat', 'Fiş', 'Ürün arama'],
    monthlyPrice: 259,
    yearlyPrice: 2590,
    trialDays: 7,
    sortOrder: 120,
    storeVisible: true,
  },
  {
    code: 'purchasing',
    slug: 'satin-alma',
    label: 'Satın Alma',
    category: 'erp',
    icon: 'ClipboardList',
    iconColor: '#CA8A04',
    description: 'Tedarikçi siparişleri ve satın alma taleplerini yönetin.',
    longDescription:
      'Satın alma talepleri, tedarikçi siparişleri ve mal kabul süreçlerini ERP akışına bağlayın.',
    audience: 'Satın alma ve tedarik ekipleri',
    features: ['Satın alma talebi', 'Tedarikçi siparişi', 'Mal kabul', 'Tedarikçi kartı'],
    monthlyPrice: 219,
    yearlyPrice: 2190,
    trialDays: 14,
    sortOrder: 130,
    storeVisible: true,
  },
  {
    code: 'finance',
    slug: 'finans',
    label: 'Finans',
    category: 'finance',
    icon: 'Wallet',
    iconColor: '#16A34A',
    description: 'Kasa, banka, cari ve tahsilat süreçlerini tek yerden yönetin.',
    longDescription:
      'Finans modülü ile kasa, banka, çek/senet, cari bakiyeler ve tahsilat-ödeme akışını izleyin.',
    audience: 'Muhasebe ve finans ekipleri',
    features: ['Kasa & banka', 'Cari', 'Tahsilat', 'Ödeme'],
    monthlyPrice: 279,
    yearlyPrice: 2790,
    trialDays: 14,
    sortOrder: 140,
    storeVisible: true,
  },
  {
    code: 'reporting',
    slug: 'gelismis-raporlama',
    label: 'Gelişmiş Raporlama',
    category: 'management',
    icon: 'BarChart3',
    iconColor: '#6366F1',
    description: 'KPI, dashboard ve gelişmiş işletme raporlarıyla karar alın.',
    longDescription:
      'Gelişmiş raporlama ile satış, stok, finans ve operasyon KPI’larını özelleştirilebilir panellerde görün.',
    audience: 'Yöneticiler ve analitik ekipler',
    features: ['KPI panelleri', 'Özel raporlar', 'Export', 'Dashboard'],
    monthlyPrice: 199,
    yearlyPrice: 1990,
    trialDays: 14,
    sortOrder: 150,
    storeVisible: true,
  },
  {
    code: 'hr',
    slug: 'insan-kaynaklari',
    label: 'İnsan Kaynakları',
    category: 'hr',
    icon: 'UserCog',
    iconColor: '#9333EA',
    description: 'Personel, izin ve bordro süreçlerini dijitalleştirin.',
    longDescription:
      'İK modülü ile personel kartları, izin talepleri ve temel insan kaynakları süreçlerini yönetin.',
    audience: 'İK ekipleri ve büyüyen şirketler',
    features: ['Personel kartı', 'İzin yönetimi', 'Organizasyon', 'Doküman'],
    monthlyPrice: 249,
    yearlyPrice: 2490,
    trialDays: 7,
    sortOrder: 160,
    storeVisible: true,
  },
  {
    code: 'hr_attendance',
    slug: 'personel-takip',
    label: 'Personel Takip',
    category: 'hr',
    icon: 'Clock',
    iconColor: '#A855F7',
    description: 'Mesai, giriş-çıkış ve personel devam takibini yapın.',
    longDescription: 'Personel devam durumu, mesai ve vardiya takibini kolaylaştırın.',
    audience: 'İK ve operasyon yöneticileri',
    features: ['Devam takibi', 'Mesai', 'Vardiya', 'Raporlar'],
    monthlyPrice: 179,
    yearlyPrice: 1790,
    trialDays: 7,
    sortOrder: 170,
    storeVisible: true,
  },
  {
    code: 'whatsapp',
    slug: 'whatsapp-merkezi',
    label: 'WhatsApp Merkezi',
    category: 'comms',
    icon: 'MessageCircle',
    iconColor: '#22C55E',
    description: 'WhatsApp konuşmalarını müşteri kartlarıyla entegre yönetin.',
    longDescription:
      'WhatsApp Merkezi ile gelen mesajları ekipçe yanıtlayın, müşteri kaydına bağlayın ve şablonlarla hızlanın.',
    audience: 'Satış, destek ve müşteri iletişim ekipleri',
    features: ['Ortak inbox', 'Müşteri eşleme', 'Şablon mesaj', 'Ekip atama'],
    monthlyPrice: 249,
    yearlyPrice: 2490,
    trialDays: 7,
    sortOrder: 180,
    storeVisible: true,
  },
  {
    code: 'projects',
    slug: 'proje-yonetimi',
    label: 'Proje Yönetimi',
    category: 'management',
    icon: 'FolderKanban',
    iconColor: '#0EA5E9',
    description: 'Projeleri, kilometre taşlarını ve ekipleri tek yerden yönetin.',
    longDescription: 'Proje panoları, görev dağılımı ve ilerleme takibi ile proje yönetimini sadeleştirin.',
    audience: 'Proje ve operasyon ekipleri',
    features: ['Proje panosu', 'Kilometre taşı', 'Ekip atama', 'İlerleme'],
    monthlyPrice: 199,
    yearlyPrice: 1990,
    trialDays: 14,
    sortOrder: 190,
    storeVisible: true,
  },
  {
    code: 'tasks',
    slug: 'gorev-yonetimi',
    label: 'Görev Yönetimi',
    category: 'management',
    icon: 'CheckSquare',
    iconColor: '#3B82F6',
    description: 'Görevleri atayın, önceliklendirin ve tamamlanma durumunu izleyin.',
    longDescription: 'Görev listeleri, öncelikler, son tarihler ve hatırlatmalarla ekip iş yükünü yönetin.',
    audience: 'Tüm ekipler',
    features: ['Görev atama', 'Öncelik', 'Son tarih', 'Hatırlatma'],
    monthlyPrice: 129,
    yearlyPrice: 1290,
    trialDays: 14,
    sortOrder: 200,
    storeVisible: true,
  },
  {
    code: 'appointments',
    slug: 'randevu',
    label: 'Randevu',
    category: 'management',
    icon: 'Calendar',
    iconColor: '#F59E0B',
    description: 'Müşteri ve iç toplantı randevularını takvimden yönetin.',
    longDescription: 'Randevu planlama, hatırlatma ve müşteri eşleştirmesi ile ajandanızı düzenleyin.',
    audience: 'Satış, servis ve ofis ekipleri',
    features: ['Takvim', 'Hatırlatma', 'Müşteri bağlama', 'Tekrarlayan randevu'],
    monthlyPrice: 99,
    yearlyPrice: 990,
    trialDays: 14,
    sortOrder: 210,
    storeVisible: true,
  },
  {
    code: 'multi_company',
    slug: 'coklu-sirket',
    label: 'Çoklu Şirket',
    category: 'management',
    icon: 'Building2',
    iconColor: '#1D4ED8',
    description: 'Birden fazla şirketi tek hesap altında yönetin.',
    longDescription:
      'Çoklu şirket ile holding veya grup şirketlerinizi aynı Bachmain hesabında ayırarak yönetin.',
    audience: 'Grup şirketleri ve holding yapıları',
    features: ['Çoklu şirket', 'Şirket geçişi', 'Ayrı cari/stok', 'Merkezi yönetim'],
    monthlyPrice: 399,
    yearlyPrice: 3990,
    trialDays: 7,
    sortOrder: 220,
    storeVisible: true,
  },
  {
    code: 'multi_branch',
    slug: 'coklu-sube',
    label: 'Çoklu Şube',
    category: 'management',
    icon: 'GitBranch',
    iconColor: '#2563EB',
    description: 'Şube bazlı stok, satış ve kullanıcı yetkilerini ayırın.',
    longDescription: 'Çoklu şube ile lokasyon bazlı operasyon, stok ve raporları yönetin.',
    audience: 'Çok şubeli perakende ve dağıtım firmaları',
    features: ['Şube yönetimi', 'Lokasyon stok', 'Şube raporları', 'Yetki ayrımı'],
    monthlyPrice: 299,
    yearlyPrice: 2990,
    trialDays: 7,
    sortOrder: 230,
    storeVisible: true,
  },
  {
    code: 'api',
    slug: 'api-entegrasyon',
    label: 'API & Entegrasyon',
    category: 'integration',
    icon: 'Plug',
    iconColor: '#475569',
    description: 'Harici sistemlerle API ve webhook entegrasyonları kurun.',
    longDescription:
      'REST API erişimi ve webhook’larla Bachmain’i e-ticaret, muhasebe veya özel yazılımlarınıza bağlayın.',
    audience: 'Teknik ekipler ve entegrasyon ihtiyacı olan firmalar',
    features: ['API erişimi', 'Webhook', 'Anahtar yönetimi', 'Dokümantasyon'],
    monthlyPrice: 349,
    yearlyPrice: 3490,
    trialDays: 7,
    sortOrder: 240,
    storeVisible: true,
  },
]

/** Geriye uyumlu add-on listesi — mağaza kataloğundan türetilir + legacy kodlar */
export const DEFAULT_ADDONS = [
  ...STORE_MODULES.map(({ storeVisible, ...rest }) => rest),
  {
    code: 'sms',
    slug: 'sms',
    label: 'SMS',
    category: 'comms',
    icon: 'Smartphone',
    iconColor: '#64748B',
    description: 'Toplu ve tekil SMS gönderimi.',
    longDescription: 'SMS bildirimleri ve kampanya mesajları.',
    audience: 'İletişim ekipleri',
    features: ['Toplu SMS', 'Şablon'],
    monthlyPrice: 290,
    yearlyPrice: 2900,
    trialDays: 7,
    sortOrder: 900,
    storeVisible: false,
  },
  {
    code: 'esign',
    slug: 'e-imza',
    label: 'E-İmza',
    category: 'integration',
    icon: 'PenLine',
    iconColor: '#64748B',
    description: 'Elektronik imza süreçleri.',
    longDescription: 'E-imza ile belge onayları.',
    audience: 'Operasyon ekipleri',
    features: ['E-imza'],
    monthlyPrice: 390,
    yearlyPrice: 3900,
    trialDays: 7,
    sortOrder: 910,
    storeVisible: false,
  },
  {
    code: 'einvoice',
    slug: 'e-fatura-modul',
    label: 'E-Fatura Modülü',
    category: 'finance',
    icon: 'Receipt',
    iconColor: '#64748B',
    description: 'E-fatura belge modülü (kontör ayrı satılır).',
    longDescription: 'E-fatura / e-arşiv belge süreçleri. Kontör paketleri ayrı sayfadadır.',
    audience: 'Muhasebe ekipleri',
    features: ['E-Fatura', 'E-Arşiv'],
    monthlyPrice: 590,
    yearlyPrice: 5900,
    trialDays: 14,
    sortOrder: 920,
    storeVisible: false,
  },
  {
    code: 'ewaybill',
    slug: 'e-irsaliye',
    label: 'E-İrsaliye',
    category: 'logistics',
    icon: 'FileOutput',
    iconColor: '#64748B',
    description: 'E-irsaliye belge süreçleri.',
    longDescription: 'E-irsaliye oluşturma ve takip.',
    audience: 'Lojistik ekipleri',
    features: ['E-İrsaliye'],
    monthlyPrice: 390,
    yearlyPrice: 3900,
    trialDays: 14,
    sortOrder: 930,
    storeVisible: false,
  },
  {
    code: 'courier',
    slug: 'kurye',
    label: 'Kurye',
    category: 'logistics',
    icon: 'Bike',
    iconColor: '#64748B',
    description: 'Kurye ve teslimat operasyonları.',
    longDescription: 'Kurye atama ve teslimat takibi.',
    audience: 'Teslimat ekipleri',
    features: ['Kurye atama'],
    monthlyPrice: 490,
    yearlyPrice: 4900,
    trialDays: 7,
    sortOrder: 940,
    storeVisible: false,
  },
]

export const DEFAULT_PLANS = [
  {
    code: 'starter',
    name: 'Starter',
    description: 'Küçük işletmeler ve yeni başlayan firmalar için temel CRM.',
    prices: {
      month: 499,
      year: 4990,
      year2: 9000,
      year3: 12900,
      year5: 19900,
      year10: 34900,
      lifetime: 49900,
    },
    maxUsers: 3,
    storageGb: 2,
    maxCompanies: 1,
    maxBranches: 1,
    maxWarehouses: 1,
    sortOrder: 1,
    active: true,
    modules: modulesForPlan('starter'),
  },
  {
    code: 'professional',
    name: 'Pro',
    description: 'Büyüyen KOBİ’ler için ERP ve operasyon paketleri.',
    prices: {
      month: 1499,
      year: 14990,
      year2: 27000,
      year3: 39000,
      year5: 59000,
      year10: 99000,
      lifetime: 149900,
    },
    maxUsers: 25,
    storageGb: 100,
    maxCompanies: 1,
    maxBranches: 3,
    maxWarehouses: 5,
    sortOrder: 2,
    active: true,
    modules: modulesForPlan('professional'),
  },
  {
    code: 'enterprise',
    name: 'Enterprise',
    description: 'Kurumsal firmalar için limitsiz ve gelişmiş özellikler.',
    prices: {
      month: 4999,
      year: 49990,
      year2: 90000,
      year3: 129000,
      year5: 199000,
      year10: 349000,
      lifetime: 0,
    },
    maxUsers: 0,
    storageGb: 0,
    maxCompanies: 0,
    maxBranches: 0,
    maxWarehouses: 0,
    sortOrder: 3,
    active: true,
    modules: modulesForPlan('enterprise'),
  },
]

export const PERIOD_MONTHS = {
  month: 1,
  year: 12,
  year2: 24,
  year3: 36,
  year5: 60,
  year10: 120,
  lifetime: 1200,
}

export function normalizePlanCode(raw) {
  const s = String(raw || '')
    .trim()
    .toLowerCase()
  if (/enter|kurum/.test(s)) return 'enterprise'
  if (/pro|profesyonel|professional|business/.test(s)) return 'professional'
  if (/free|trial|deneme/.test(s)) return 'starter'
  if (/start|başlangıç|baslangic/.test(s)) return 'starter'
  if (['starter', 'professional', 'enterprise'].includes(s)) return s
  return 'professional'
}

export function displayPlanName(code) {
  const map = { starter: 'Starter', professional: 'Professional', enterprise: 'Enterprise' }
  return map[normalizePlanCode(code)] || 'Professional'
}
